# Домашнє завдання: Внесення оновлень в БД і робота з транзакціями

Це ДЗ передбачене під виконання на локальній машині. Виконання з Google Colab буде суттєво ускладнене.

## Підготовка
1. Переконайтесь, що у вас встановлены необхідні бібліотеки:
   ```bash
   pip install sqlalchemy pymysql pandas matplotlib seaborn python-dotenv
   ```

2. Створіть файл `.env` з параметрами підключення до бази даних classicmodels. Базу даних ви можете отримати через

  - docker-контейнер згідно існтрукції в [документі](https://www.notion.so/hannapylieva/Docker-1eb94835849480c9b2e7f5dc22ee4df9), також відео інструкції присутні на платформі - уроки "MySQL бази, клієнт для роботи з БД, Docker і ChatGPT для запитів" та "Як встановити Docker для роботи з базами даних без терміналу"
  - або встановивши локально цю БД - для цього перегляньте урок "Опціонально. Встановлення MySQL та  БД Сlassicmodels локально".
  
  Приклад `.env` файлу ми створювали в лекції. Ось його обовʼязкове наповнення:
    ```
    DB_HOST=your_host
    DB_PORT=3306 або 3307 - той, який Ви налаштували
    DB_USER=your_username
    DB_PASSWORD=your_password
    DB_NAME=classicmodels
    ```
  Якщо ви створили цей файл під час перегляду лекції - **новий створювати не треба**. Замініть лише назву БД, або пропишіть назву в коді створення підключення (замість отримання назви цільової БД зі змінних оточення). Але переконайтесь, що до `.env` файл лежить в тій самій папці, що і цей ноутбук.

  **УВАГА!** НЕ копіюйте скрит для **створення** `.env` файлу. В лекції він наводиться для прикладу. І давалось пояснення, що в реальних проєктах ми НІКОЛИ не пишемо доступи до бази в коді. Копіювання скрипта для створення `.env` файлу сюди в ДЗ буде вважатись грубою помилкою і ми зніматимемо бали.

3. Налаштуйте підключення через SQLAlchemy до БД за прикладом в лекції.

Рекомендую вивести (відобразити) змінну engine після створення. Вона має бути не None! Якщо None - значить у Вас не підтягнулись налаштування з .env файла.

Ви також можете налаштувати параметри підключення до БД без .env файла, просто прописавши текстом в відповідних місцях. Це - не рекомендований підхід.

In [1]:
import os
print(os.getcwd())
print(os.path.exists(".env"))

C:\Users\Вальчук Богдан
True

In [2]:
import sqlalchemy, pymysql, pandas, matplotlib, seaborn, dotenv
print("Все на місці")

Все на місці

In [3]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

load_dotenv()


def create_connection():
    # Отримуємо параметри з environment variables
    host = os.getenv('DB_HOST', 'localhost')
    port = os.getenv('DB_PORT', '3307')
    user = os.getenv('DB_USER')
    password = os.getenv('DB_PASSWORD')
    database = 'classicmodels'

    if not all([user, password, database]):
        raise ValueError("Не всі параметри БД задані в .env файлі!")

    # Створюємо connection string
    connection_string = f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}"

    # Створюємо engine з connection pooling
    engine = create_engine(
        connection_string,
        pool_size=2,
        max_overflow=20,
        pool_pre_ping=True,
        echo=False
    )

    # Тестуємо підключення
    try:
        with engine.connect() as conn:
            result = conn.execute(text("SELECT 1"))
            result.fetchone()

        print("✅ Підключення до БД успішне!")
        print(f"🔗 {user}@{host}:{port}/{database}")
        print(f"⚡ Engine: {engine}")

        return engine

    except Exception as e:
        print(f"❌ Помилка підключення: {e}")оновлення
        return None


# Створюємо підключення
engine = create_connection()
engine

✅ Підключення до БД успішне!
🔗 root@127.0.0.1:3307/classicmodels
⚡ Engine: Engine(mysql+pymysql://root:***@127.0.0.1:3307/classicmodels)

Engine(mysql+pymysql://root:***@127.0.0.1:3307/classicmodels)

### Завдання 1: Оновлення інформації про клієнта (2 бали)

**Створіть функцію для оновлення контактної інформації клієнта за його номером** з наступними можливостями:
- Оновлення телефону клієнта
- Оновлення email (якщо поле існує в таблиці)

Опціонально, якщо вам хочеться більше практики:
- Логування змін в окрему таблицю

Використайте підхід з параметризованими запитами через `text()` та `UPDATE` оператор. Не забудьте на початку перевірити чи існує клієнт з таким номером в базі - це хороша практика.

Отримати всі колонки, які існують в таблиці ви можете наступним запитом
```
  SELECT COLUMN_NAME, DATA_TYPE
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'customers'
```

Запустіть функцію і продемонструйте її роботу, запустивши SELECT, який допоможе це зробити.

In [15]:
 # Спочатку перевіряємо чи існує співробітник (окремо від транзакції)
check_query = text("""
    SELECT COLUMN_NAME, DATA_TYPE
      FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'customers' 
      AND TABLE_SCHEMA = 'classicmodels'
""")

columns_df = pd.read_sql(check_query, engine)
display(columns_df)

               COLUMN_NAME DATA_TYPE
0           customerNumber       int
1             customerName   varchar
2          contactLastName   varchar
3         contactFirstName   varchar
4                    phone   varchar
5             addressLine1   varchar
6             addressLine2   varchar
7                     city   varchar
8                    state   varchar
9               postalCode   varchar
10                 country   varchar
11  salesRepEmployeeNumber       int
12             creditLimit   decimal

Колонки email у таблиці немає, тому функція завжди оновлюватиме телефон, а email лише тоді, коли таке поле існує.

In [16]:
def update_customer_contact(customer_number, phone=None, email=None):
    with engine.begin() as conn:
        # 1. Перевіряємо, чи існує клієнт
        customer = conn.execute(
            text("SELECT customerNumber FROM customers WHERE customerNumber = :num"),
            {"num": customer_number}
        ).fetchone()

        if customer is None:
            print(f"Клієнта з номером {customer_number} не знайдено")
            return

        # 2. Оновлюємо телефон
        if phone is not None:
            conn.execute(
                text("UPDATE customers SET phone = :phone WHERE customerNumber = :num"),
                {"phone": phone, "num": customer_number}
            )
            print(f"Телефон клієнта {customer_number} оновлено: {phone}")

        # 3. Оновлюємо email, лише якщо така колонка існує
        if email is not None:
            has_email = conn.execute(text("""
                SELECT COUNT(*)
                FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_SCHEMA = 'classicmodels'
                  AND TABLE_NAME = 'customers'
                  AND COLUMN_NAME = 'email'
            """)).scalar()

            if has_email:
                conn.execute(
                    text("UPDATE customers SET email = :email WHERE customerNumber = :num"),
                    {"email": email, "num": customer_number}
                )
                print(f"Email клієнта {customer_number} оновлено: {email}")
            else:
                print("Поля email у таблиці customers немає, email не оновлено")

In [17]:
## Демонстрація (клієнт 103):
select_query = text("""
    SELECT customerNumber, customerName, phone
    FROM customers
    WHERE customerNumber = :num
""")

print("ДО оновлення:")
display(pd.read_sql(select_query, engine, params={"num": 103}))

update_customer_contact(103, phone="+49 381 1234567", email="test@mail.com")

print("ПІСЛЯ оновлення:")
display(pd.read_sql(select_query, engine, params={"num": 103}))

# Неіснуючий клієнт
update_customer_contact(99999, phone="000")

ДО оновлення:

   customerNumber       customerName       phone
0             103  Atelier graphique  40.32.2555

Телефон клієнта 103 оновлено: +49 381 1234567
Поля email у таблиці customers немає, email не оновлено
ПІСЛЯ оновлення:

   customerNumber       customerName            phone
0             103  Atelier graphique  +49 381 1234567

Клієнта з номером 99999 не знайдено

### Завдання 2: Створення нового замовлення з транзакцією (5 балів)

**Реалізуйте процес створення нового замовлення** з наступними кроками в одній транзакції:
- Створення запису в таблиці `orders`
- Додавання товарних позицій в `orderdetails`
- Перевірка наявності товарів на складі
- Зменшення кількості товарів на складі

Запустіть процес з тестовими даними і продемонструйте через SELECT, що процес успішно відпрацював і були виконані необхідні операції.

In [18]:
for table in ["orders", "orderdetails", "products"]:
    query = text("""
        SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, EXTRA
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'classicmodels'
          AND TABLE_NAME = :table
    """)
    print(table)
    display(pd.read_sql(query, engine, params={"table": table}))

orders

      COLUMN_NAME DATA_TYPE IS_NULLABLE EXTRA
0     orderNumber       int          NO
1       orderDate      date          NO
2    requiredDate      date          NO
3     shippedDate      date         YES
4          status   varchar          NO
5        comments      text         YES
6  customerNumber       int          NO

orderdetails

       COLUMN_NAME DATA_TYPE IS_NULLABLE EXTRA
0      orderNumber       int          NO
1      productCode   varchar          NO
2  quantityOrdered       int          NO
3        priceEach   decimal          NO
4  orderLineNumber  smallint          NO

products

          COLUMN_NAME DATA_TYPE IS_NULLABLE EXTRA
0         productCode   varchar          NO
1         productName   varchar          NO
2         productLine   varchar          NO
3        productScale   varchar          NO
4       productVendor   varchar          NO
5  productDescription      text          NO
6     quantityInStock  smallint          NO
7            buyPrice   decimal          NO
8                MSRP   decimal          NO

In [19]:
def create_order(customer_number, items):
    with engine.begin() as conn:
        # 1. Перевіряємо, чи існує клієнт
        customer = conn.execute(
            text("SELECT customerNumber FROM customers WHERE customerNumber = :num"),
            {"num": customer_number}
        ).fetchone()
        if customer is None:
            raise ValueError(f"Клієнта {customer_number} не існує")

        # 2. Новий номер замовлення = найбільший існуючий + 1
        order_number = conn.execute(
            text("SELECT MAX(orderNumber) + 1 FROM orders")
        ).scalar()

        # 3. Створюємо запис в orders
        conn.execute(text("""
            INSERT INTO orders (orderNumber, orderDate, requiredDate, status, customerNumber)
            VALUES (:order_num, CURDATE(), DATE_ADD(CURDATE(), INTERVAL 7 DAY), 'In Process', :cust)
        """), {"order_num": order_number, "cust": customer_number})

        # 4. Для кожного товару: перевірка складу -> orderdetails -> списання
        for line_number, item in enumerate(items, start=1):
            product = conn.execute(
                text("SELECT quantityInStock, MSRP FROM products WHERE productCode = :code"),
                {"code": item["productCode"]}
            ).fetchone()

            if product is None:
                raise ValueError(f"Товару {item['productCode']} не існує")
            if product.quantityInStock < item["quantity"]:
                raise ValueError(
                    f"Недостатньо {item['productCode']} на складі: "
                    f"є {product.quantityInStock}, потрібно {item['quantity']}"
                )

            conn.execute(text("""
                INSERT INTO orderdetails (orderNumber, productCode, quantityOrdered, priceEach, orderLineNumber)
                VALUES (:order_num, :code, :qty, :price, :line)
            """), {"order_num": order_number, "code": item["productCode"],
                   "qty": item["quantity"], "price": product.MSRP, "line": line_number})

            conn.execute(text("""
                UPDATE products
                SET quantityInStock = quantityInStock - :qty
                WHERE productCode = :code
            """), {"qty": item["quantity"], "code": item["productCode"]})

    print(f"Замовлення {order_number} успішно створено")
    return order_number

In [20]:
## Демонстрація. Товари S10_1678 і S10_1949 є в базі, клієнт той самий, 103:
items = [
    {"productCode": "S10_1678", "quantity": 5},
    {"productCode": "S10_1949", "quantity": 3},
]
stock_query = text("""
    SELECT productCode, productName, quantityInStock
    FROM products WHERE productCode IN ('S10_1678', 'S10_1949')
""")

print("Склад ДО:")
display(pd.read_sql(stock_query, engine))

new_order = create_order(103, items)

print("Нове замовлення в orders:")
display(pd.read_sql(text("SELECT * FROM orders WHERE orderNumber = :n"), engine, params={"n": new_order}))

print("Позиції в orderdetails:")
display(pd.read_sql(text("SELECT * FROM orderdetails WHERE orderNumber = :n"), engine, params={"n": new_order}))

print("Склад ПІСЛЯ:")
display(pd.read_sql(stock_query, engine))

Склад ДО:

  productCode                            productName  quantityInStock
0    S10_1678  1969 Harley Davidson Ultimate Chopper             7933
1    S10_1949               1952 Alpine Renault 1300             7305

Замовлення 10426 успішно створено
Нове замовлення в orders:

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber
0,10426,2026-09-23,2026-09-30,None,In Process,None,103

Позиції в orderdetails:

   orderNumber productCode  quantityOrdered  priceEach  orderLineNumber
0        10426    S10_1678                5       95.7                1
1        10426    S10_1949                3      214.3                2

Склад ПІСЛЯ:

  productCode                            productName  quantityInStock
0    S10_1678  1969 Harley Davidson Ultimate Chopper             7928
1    S10_1949               1952 Alpine Renault 1300             7302

In [22]:
## Перевірка відкату. Замовляємо більше, ніж є на складі:
try:
    create_order(103, [
        {"productCode": "S10_1678", "quantity": 1},
        {"productCode": "S10_1949", "quantity": 999999},
    ])
except ValueError as e:
    print("Помилка:", e)

print("Останнє замовлення в базі:")
display(pd.read_sql(text("SELECT MAX(orderNumber) AS last_order FROM orders"), engine))
display(pd.read_sql(stock_query, engine))

Помилка: Недостатньо S10_1949 на складі: є 7302, потрібно 999999
Останнє замовлення в базі:

   last_order
0       10426

  productCode                            productName  quantityInStock
0    S10_1678  1969 Harley Davidson Ultimate Chopper             7928
1    S10_1949               1952 Alpine Renault 1300             7302